server:
  port: 9081
dubbo:
  application:
    name: product-consumer
  registry:
    address: zookeeper://192.168.2.146:2181
fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list: 192.168.2.144:22122
imageServer: http://192.168.2.144:8888
