server:
  port: 8083
dubbo:
  application:
    name: user-service
  registry:
    address: zookeeper://192.168.2.146:2181
  protocol:
    port: 20883

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qf-v6?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 192.168.2.147
    port: 6379
    password: java1906
    jedis:
      pool:
        max-active: 20
  rabbitmq:
    host: 192.168.2.143
    port: 5672
    username: java1906
    password: 123456
    virtual-host: j1906
activeAccountServer: http://localhost:8086/email/active?uuid=
