server:
  port: 8084
dubbo:
  application:
    name: search-service
  registry:
    address: zookeeper://192.168.2.146:2181
  protocol:
    port: 20884
spring:
  data:
    solr:
      host: http://192.168.2.154:8983/solr/ik_core
  datasource:
    url: jdbc:mysql://localhost:3306/qf-v6?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  rabbitmq:
    host: 192.168.2.143
    port: 5672
    username: java1906
    password: 123456
    virtual-host: j1906
imageServer: http://192.168.2.144:8888
